version: '3.7'
services:
  database:
    image: mysql:5.7
    volumes:
      - ./storage/database:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laravel
  app:
    build: docker
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=database
    depends_on:
      - database
  web:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - 80:80
    depends_on:
      - app
