version: '3.7'
services:
  database:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laravel
  app:
    build: docker/app
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=database
    depends_on:
      - database
  web:
    build: docker/web
    volumes:
      - .:/var/www
    ports:
      - 80:80
    depends_on:
      - app
